### ISSUE TITLE
Worlds tab only displays 1 world unless refreshed

### ISSUE THREAD

**Issue by ghost** [triwave/MakersofMario#50]
See subject.
### Example:

Before (_Always shown when first visiting Worlds_)
![2016-06-28--090113_1600x900](https://cloud.githubusercontent.com/assets/18563664/16418349/659ed90e-3d17-11e6-8096-fa989b94e5b9.png)

After (_subsequent loads / refreshes_)
![2016-06-28--090143_1600x900](https://cloud.githubusercontent.com/assets/18563664/16418352/6e84c3a8-3d17-11e6-8d97-d99780b124d6.png)

**Comment by jaku** [comment]
thats normal. that is just a random search. the random search is for words like "jaku" and "poo" we are adding random searches but at the time we only had a few worlds.

**Comment by SapphireTactician** [comment]
So it's normal that the initial result is always "Troll Series One" (*first screenshot before refresh*), giving one, single, world an unfair visibility advantage over all the other worlds?

**Comment by SapphireTactician** [comment]
>Random search

I can't see a keyword search being truly random and without bias unless it pulls from random tags / themes / labels used instead of pre-defined keywords.

Regardless, I feel unless someone explicitly enters a search term, the results should be empty - that way there's no bias and no makers get an unfair visibility advantage.

That being said, having a "random" search where the default view / terms (*when it's actually working after the refresh instead of being consistently stuck on a single world*) are so conveniently keywords being the maintainer of the project and his buddies, comes off as a shameless circlejerk that anyone with at least half a brain can see through.
