### ISSUE TITLE
Cannot scroll or advance lists

### ISSUE THREAD

**Issue by MYCRAFTisbest** [triwave/MakersofMario#9]
Issue occurs on:

My Levels, Level Search, World Search, World Management (levels in the world), (presumably worlds if you have enough of them)

Only the top results appear. There is no way to advance any further. This is especially noticeable with My Levels and with trying to manage a world.

**Comment by jaku** [comment]
My Levels is now limited to showing 100 results instead of 10.

Level search \ World search is increased to 20. 

Everything else is also limited to 20.

Some results will be updated to allow paging but things such as search will most likely stay at 20 and will just require you to be more specific. More options on search options is coming soon.

NOT FIXED, just better.

**Comment by MYCRAFTisbest** [comment]
Well, at least that fixed My Levels. You know, unless you just keep deleting levels and give yourself 101 levels.

Definitely a step forwards

**Comment by jaku** [comment]
I think best way to do this is with pagnation for current levels but also have a levels graveyard type thing. to show your past/remove/deleted whatever levels that we may have data for.
